POST http://localhost:9090/api/search/suggest
Content-Type: application/json

{
  "content": "cx"
}

###
POST http://localhost:9090/api/search/
Content-Type: application/json

{
  "scene": "ROBOT",
  "content": "成县cx"
}

###
GET http://localhost:9090/api/search/init
